### PR TITLE
Intermediate build representation

### PR DESCRIPTION
**Pull request by andreypopp**
**DO NOT MERGE YET**

TODO:

* [x] Make `esy-ocaml-project` buildable with it.
* [x] Build packages in parallel
* [x] Rewrite files in packages in parallel
* [x] Fancy reporting (reuse Yarn's progress bar?)
* [x] Execute commands without `/bin/bash` (requires env var expansion)
* [x] Do not use`rsync` in JS builder
* [x] Add minimal variable expansion modifiers to power opam conversed packages — `${name:-default}` for example.
* [x] Fix deprecation warnings when generating env
* [x] Add sandboxing
* [x] Make sure linked workflow is supported
* [x] Check mtimes for local packages
* [x] Link artefacts into `_build`, `_install` from local & global stores (make sure it symlinks even if builds are cached)
* [ ] Add env validation
* [ ] Versioned store (regression)

This PR likely regresses on some parts of functionality already present in `esy` branch but it makes add those back more easily, I believe, also in a testable manner.

### Intermediate build representation

`esy/build-repr` now has intermediate build representation. We had it before (`esy/Sandbox` module) too but it was mostly a crawled dep graph (a collection of `package.json` files) which were interpreted by various parts of Esy differently and non-uniformly. Now it is more consistent.

`esy/build-sandbox` is a rewrite of `esy/Sandbox` which crawls a directory and represents it in terms of intermediate build repr.

`esy/build-config` defines a configuration interface for builds — right now it only abstracts away path generation. Env calculation and makefile build ejection uses it to generate all the paths.

`esy/environment` is a former `esy/PackageEnvironment` (just a change to adhere to Yarn code style).

`esy/builders/makefile-builder` is a build ejection code to Makefile based build which is now has a strictly defined interface (see `esy/build-repr` types).

### JS based builder

This is an alternative to `Makefile` ejection — builds are orchestrated by JS code and thus doesn't (or won't) require `python`, `rsync` or even `bash` (not yet there and only for those package which can be built without those tools).

### CODE REVIEW

**Comment by jordwalke** [comment]
What specifically regresses? Are you aware of anything?

**Comment by andreypopp** [comment]
@jordwalke I didn't test symlink/local deps workflow with it yet

**Comment by jordwalke** [comment]
We can leave the JS builder as a work-in-progress experimental feature disabled by default, right? (And commit this first, and come back to the JS builder after landing this refactor?)

**Comment by andreypopp** [comment]
@jordwalke JS builder already builds `esy-ocaml-project`. I think it is valuable to have more than a single builder working as it validates the build model. Also JS builder has fancier reporting:

screen shot 2017-03-28 at 01 31 32

Remaining todos are not specific to JS builder mostly.

**Comment by andreypopp** [comment]
Another thing we need to decide on is the blessed build system — `solvuu-build` while being awesome is incompatible with Esy (in an efficient manner) as it doesn't allow to build out of source — `_build` directory is hardcoded and it even mentioned in project's README.

**Comment by IwanKaramazow** [comment]
I also noticed `solvuu-build` not always succeeding in building, we might want to drop it.

**Comment by andreypopp** [comment]
@IwanKaramazow yeah, any suggestions? I want to look into topkg probably.

**Comment by IwanKaramazow** [comment]
I was thinking of topkg actually, seems like a solid option for now.
(Personally I don't care for the .merlin generation atm)

**Comment by andreypopp** [comment]
Move esy-ocaml-project to use ocamlbuild directly. Another idea is to try to use jbuilder if it allows to configure its build output directory.

**Comment by IwanKaramazow** [comment]
I looked into jbuilder, it's pretty great & works with esy! Even `.merlin` gets generated.
I'm still figuring out how to actually write these rules, but the `jbuild`config file (located in my `src` folder) from below automatically builds an executable `_build/default/src/helloworld.exe`
```
  1 (jbuild_version 1)
  2
  3 (rule
  4  ((targets (lala.ml))
  5   (deps    (lala.re))
  6   (action  (system "refmt --parse re --print ml ${<} > lala.ml"))))
  7
  8 (rule
  9  ((targets (lolo.ml))
 10   (deps    (lolo.re))
 11   (action  (system "refmt --parse re --print ml ${<} > lolo.ml"))))
 12
 13 (executables
 14   ((names (helloworld))
 15     (libraries (sqlite3))))
~
```

`helloworld.ml` depends on `lala.re` & `lolo.re` in this case. it's as easy as sticking 
```
  3   "esy": {
  4     "build": [
  5       "jbuilder build src/helloworld.exe"
  6     ]
  7   },
```
 in my package.json. We should put esy-ocaml-project on it.

**Comment by andreypopp** [comment]
@IwanKaramazow so the main issue with jbuilder + esy as I see is that jbuilder can't be instructed to put build artefacts in a location other than `$PWD/_build`, which forces to use esy's `buildsInSource: true` config which isn't nice.

**Comment by IwanKaramazow** [comment]
Ah makes sense, I might have been prematurely excited.

**Comment by jordwalke** [comment]
That might not make jbuilder the best example to demonstrate esy's cool features. But it could still be the right choice for ReasonProject because our aim for that example isn't performance but dev experience including everything like Merlin generation.

**Comment by jordwalke** [comment]
What was this item on the checklist?

"Link artefacts into _build, _install from local & global stores (make sure it symlinks even if builds are cached)"

**Comment by andreypopp** [comment]
Create a link farm from stores into the sandbox dir.

**Comment by jordwalke** [comment]
Would that just be to increase debug-ability?

**Comment by andreypopp** [comment]
> Would that just be to increase debug-ability?

Mostly, yes. For sandbox's root build it's needed because you need to access the artefacts somehow.

**Comment by andreypopp** [comment]
Rebased on top of the current `esy` branch. Made sure `reason-cli` & `esy-ocaml-project` work.

**Pull request merged**
