### PR TITLE
Update to latest version of FastReplaceString

### PR DESCRIPTION
**Pull request by IwanKaramazow**
Shouldn't segfault, is unix agnostic & blazing fast.

### CODE REVIEW

**Comment by jordwalke** [comment]
I manually bumped the version:

https://github.com/reasonml/esy/commit/40cb06a94d90028eff755be7eddca17092fea6dc#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

We currently commit to the esy branch, and then we separately build and publish releases (we don't commit the result of make beta-release to master/esy branch). I wish it was a little simpler so that we didn't need a separate "publish/release" step.

**Comment by jordwalke** [comment]
I think line 445 of buildEjectCommand/index.js needs to change to .cpp. Fixing in the manual update.

**Comment by jordwalke** [comment]
So even after fixing line 445, there's an error when running gcc.
What's really annoying is that the gcc command redirects to dev null so I couldn't catch it easily

I followed the instructions to debug failed builds by running:

`esy build-eject` and then `make -f ./node_modules/.cache/_esy/build-eject/Makefile` to see which commands make was actually running. Which I found out it ran:

```
g++ -Ofast -o /Users/me/.npm-packages/lib/node_modules/reason-cli/actualInstall/node_modules/.cache/_esy/build-eject//bin/fastreplacestring.exe -x c /Users/me/.npm-packages/lib/node_modules/reason-cli/actualInstall/node_modules/.cache/_esy/build-eject//bin/fastreplacestring.cpp 2> /dev/null;
```

When I run that manually I get this error:

```
/Users/me/.npm-packages/lib/node_modules/reason-cli/actualInstall/node_modules/.cache/_esy/build-eject//bin/fastreplacestring.cpp:1:10: fatal error: 'cstdio' file not found
#include <cstdio>
         ^
1 error generated.
```

**Comment by jordwalke** [comment]
I think it needed to specify `-x c++` instead of `-x c`. I manually added that into master. Will try one more time. Here's that release that does so: https://github.com/reasonml/esy/releases/tag/beta-v0099b50

Here's the travis job to test it: https://travis-ci.org/reasonml/reason-cli/builds/224160690

(I think it might be segfaulting)

**Comment by wokalski** [comment]
There should be no flag. Neither `-x c` nor `-x c++`. C++ is implied by `g++` and the extension.

**Pull request closed without merging**
