### PR TITLE
Reduce env size

### PR DESCRIPTION
**Pull request by andreypopp**
Previously we had `$pkg__{lib,bin,...}` vars but that results in huge environments which hit `ARG_MAX` restriction on large dep graphs. Now we use `$pkg__install/{lib,bin,...}` instead. That's less flexible — we specify installation directory structure — but results in much smaller env size.

This is also should be reflected in PJC spec.

Test plan:
* Clone `esy-ocaml-project`
* `esy add @opam-alpha/cohttp`
* `esy build` — this shouldn't fail

cc @sgroove

### CODE REVIEW

**Comment by jordwalke** [comment]
> "`esy build` — this shouldn't fail"

So it worked!?

**Review by jordwalke — APPROVED** [review]
Looks awesome. I will merge and test as well!

**Comment by andreypopp** [comment]
Yep, I tested it and it works. Builds do not fail on large dep graphs. One thing I wanted to add back is expansion for `$pkg__{lib,bin,...}` as we discussed — otherwise I feel some already published packages may fail (which rely on those vars).

**Comment by jordwalke** [comment]
@andreypopp what about packages like this?

https://github.com/esy-ocaml/substs/blob/master/package.json

**Comment by jordwalke** [comment]
I think the problem is that `reason-cli` still depends on that even right now, so we can't update it.

**Comment by jordwalke** [comment]
I just tried on Sean's project, and substs failed because it was pulling from that package.json (should it not be failing?)

**Comment by jordwalke** [comment]
We could update all the miscellaneous if we cut a reason-cli version immediately after, but I'd need to test the reason-cli for a while to make sure it's very stable before cutting a release.

**Comment by andreypopp** [comment]
Let's revert this for now — I'll add expansion for vars instead of removing
then.

**Comment by jordwalke** [comment]
Okay - btw I think the variable expansion is good, and gives us the ability to actually use the opam syntax exactly (perhaps as a second step). Changing it to use the opam syntax might be better as a second step because it too will have that versioning challenge of updating the esy-ocaml branches of substs etc.

**Comment by jordwalke** [comment]
Although I wouldn't mind sticking with env vars either (especially if string replacing them at eject time removes their number). Env vars are at least ubiquitous.

**Comment by jordwalke** [comment]
Reverted here: https://github.com/reasonml/esy/pull/12

**Pull request merged**
